from typing import Any, Optional, Union

from scalecodec.base import ScaleType, ScaleDecoder
from scalecodec._scale_bytes import ScaleBytes

# --- Primitives (from _primitives.pyx) ---
class H160(ScaleType[str]): ...
class H256(ScaleType[str]): ...
class H512(ScaleType[str]): ...
class Bool(ScaleType[bool]): ...
class U8(ScaleType[int]): ...
class U16(ScaleType[int]): ...
class U32(ScaleType[int]): ...
class U64(ScaleType[int]): ...
class U128(ScaleType[int]): ...
class U256(ScaleType[int]): ...
class I8(ScaleType[int]): ...
class I16(ScaleType[int]): ...
class I32(ScaleType[int]): ...
class I64(ScaleType[int]): ...
class I128(ScaleType[int]): ...
class I256(ScaleType[int]): ...
class F32(ScaleType[float]): ...
class F64(ScaleType[float]): ...

# --- Compact (from _compact.pyx) ---
class Compact(ScaleType[int]): ...
class CompactU32(Compact): ...

# --- Core types (from types.pyx) ---
class Struct(ScaleType[dict[str, Any]]): ...
class Enum(ScaleType[dict[str, Any]]): ...
class Tuple(ScaleType[tuple[Any, ...]]): ...
class Set(ScaleType[dict[str, Any]]): ...
class Vec(ScaleType[list[Any]]): ...
class BoundedVec(Vec): ...
class BitVec(ScaleType[str]): ...
class Option(ScaleType[Optional[Any]]): ...
class Bytes(ScaleType[str]): ...
class Str(Bytes): ...
class String(Str): ...
class OptionBytes(ScaleType[Optional[str]]): ...
class HexBytes(ScaleType[str]): ...
class CallBytes(ScaleType[str]): ...
class RawBytes(ScaleType[str]): ...
class OpaqueCall(Bytes): ...
class FixedLengthArray(ScaleType[Any]): ...
class Null(ScaleType[None]): ...
class TypeNotSupported(ScaleType[None]): ...
class Era(ScaleType[dict[str, Any]]): ...
class Map(ScaleType[dict[str, Any]]): ...
class HashMap(Map): ...
class BTreeMap(Map): ...
class BoundedBTreeMap(BTreeMap): ...
class BTreeSet(ScaleType[list[Any]]): ...
class Data(Enum): ...
class StorageHasher(Enum): ...
class Conviction(Enum): ...
class LogDigest(Enum): ...

# --- Account / Address types ---
class GenericAccountId(H256): ...
class GenericEthereumAccountId(H160): ...
class GenericAccountIndex(U32): ...
class MultiAccountId(GenericAccountId): ...
class GenericAddress(ScaleType[Any]): ...
class AccountIdAddress(GenericAddress): ...
class RawAddress(GenericAddress): ...
class GenericMultiAddress(Enum): ...

# --- Call / Extrinsic / Event ---
class GenericCall(ScaleType[dict[str, Any]]): ...
class GenericExtrinsic(ScaleType[dict[str, Any]]): ...
class Extrinsic(GenericExtrinsic): ...
class GenericExtrinsicV4(Struct): ...
class GenericVote(U8): ...
class GenericEvent(Enum): ...
class GenericScaleInfoEvent(Enum): ...
class GenericEventRecord(Struct): ...
class EventRecord(Struct): ...

# --- Block / Digest ---
class GenericBlock(ScaleType[dict[str, Any]]): ...
class GenericConsensusEngineId(FixedLengthArray): ...
class GenericSealV0(Struct): ...
class GenericConsensus(Struct): ...
class GenericSeal(Struct): ...
class GenericPreRuntime(Struct): ...

# --- Contracts ---
class GenericContractExecResult(Enum): ...
class GenericContractExecResultV2(Struct): ...
class WrapperKeepOpaque(Struct): ...

# --- Compact helpers ---
class CompactMoment(CompactU32): ...
class ProposalPreimage(Struct): ...

# --- Scale info / Registry types ---
class GenericStringType(String): ...
class GenericRegistryType(Struct): ...
class GenericField(Struct): ...
class GenericVariant(Struct): ...
class GenericTypeDefComposite(Struct): ...
class GenericTypeDefVariant(Struct): ...
class GenericFunctionArgumentMetadata(Struct): ...
class GenericFunctionMetadata(Struct): ...
class ScaleInfoCallMetadata(Struct): ...
class ScaleInfoPalletErrorMetadata(Struct): ...
class ScaleInfoPalletEventMetadata(Struct): ...
class GenericRuntimeCallDefinition(Struct): ...
class GenericEventMetadata(Struct): ...
class GenericErrorMetadata(Struct): ...
class GenericModuleConstantMetadata(Struct): ...
class ScaleInfoModuleConstantMetadata(GenericModuleConstantMetadata): ...
class ScaleInfoFunctionArgumentMetadata(GenericFunctionArgumentMetadata): ...

# --- Metadata ---
class GenericPalletMetadata(Struct): ...
class ScaleInfoPalletMetadata(GenericPalletMetadata): ...
class GenericStorageEntryMetadata(Struct): ...
class ScaleInfoStorageEntryMetadata(GenericStorageEntryMetadata): ...
class GenericMetadataAll(Enum): ...

class GenericMetadataVersioned(Tuple):
    def __getitem__(self, item: Any) -> Any: ...
    @property
    def portable_registry(self) -> Optional[Any]: ...
    @property
    def pallets(self) -> list[GenericPalletMetadata]: ...
    def get_metadata(self) -> GenericMetadataAll: ...
    def get_metadata_pallet(self, name: str) -> GenericPalletMetadata: ...
    def get_pallet_by_index(self, index: int) -> GenericPalletMetadata: ...
    def get_signed_extensions(self) -> dict[str, dict[str, Optional[str]]]: ...
    @property
    def call_index(self) -> Any: ...
    @property
    def event_index(self) -> Any: ...
    def get_module_error(self, module_index: int, error_index: int) -> Any: ...