from typing import Any, Optional, Union

from scalecodec.base import ScaleType, ScaleDecoder
from scalecodec._scale_bytes import ScaleBytes

class Struct(ScaleType): ...
class Enum(ScaleType): ...
class Tuple(ScaleType): ...
class Set(ScaleType): ...
class Vec(ScaleType): ...
class Option(ScaleType): ...
class Bytes(ScaleType): ...
class String(ScaleType): ...
class Bool(ScaleType): ...
class Compact(ScaleType): ...
class H256(ScaleType): ...
class H160(ScaleType): ...
class U8(ScaleType): ...
class U16(ScaleType): ...
class U32(ScaleType): ...
class U64(ScaleType): ...
class U128(ScaleType): ...
class U256(ScaleType): ...
class I8(ScaleType): ...
class I16(ScaleType): ...
class I32(ScaleType): ...
class I64(ScaleType): ...
class I128(ScaleType): ...
class FixedLengthArray(ScaleType): ...
class GenericAccountId(H256): ...
class GenericBlock(ScaleType): ...
class GenericCall(ScaleType): ...
class GenericExtrinsic(ScaleType): ...
class GenericEvent(Enum): ...
class GenericMultiAddress(Enum): ...
class GenericPalletMetadata(Struct): ...
class ScaleInfoPalletMetadata(GenericPalletMetadata): ...
class GenericStorageEntryMetadata(Struct): ...
class GenericRegistryType(Struct): ...
class GenericMetadataAll(Enum): ...

class GenericMetadataVersioned(Tuple):
    def __getitem__(self, item: Any) -> Any: ...
    @property
    def portable_registry(self) -> Optional[Any]: ...
    @property
    def pallets(self) -> list[GenericPalletMetadata]: ...
    def get_metadata(self) -> GenericMetadataAll: ...
    def get_metadata_pallet(self, name: str) -> GenericPalletMetadata: ...
    def get_pallet_by_index(self, index: int) -> GenericPalletMetadata: ...
    def get_signed_extensions(self) -> dict[str, dict[str, Optional[str]]]: ...
    @property
    def call_index(self) -> Any: ...
    @property
    def event_index(self) -> Any: ...
    def get_module_error(self, module_index: int, error_index: int) -> Any: ...
